export const techMap: Map<string, string> = new Map([
  ["Ansible", "ansible.svg"],
  ["AWS Certified Dev - Associate", "aws-dva-c02.png"],
  ["AWS", "aws.svg"],
  ["AWS EC2", "aws.svg"],
  ["Bash/Shell", "bash.svg"],
  ["Certified K8s Administrator", "cka.avif"],
  ["Certified K8s Application Dev", "ckad.avif"],
  ["Cloudflare", "cloudflare.svg"],
  ["Codecov", "codecov.svg"],
  ["C++", "cpp.svg"],
  ["CSS", "css.svg"],
  ["Docker", "docker.svg"],
  ["Figma", "figma.svg"],
  ["Flask", "flask.svg"],
  ["GitHub Actions", "gha.svg"],
  ["Go", "go.svg"],
  ["HTML", "html.svg"],
  ["Java", "java.svg"],
  ["Kubernetes", "kubernetes.svg"],
  ["Linux", "linux.png"],
  ["Locust", "locust.png"],
  ["microk8s", "microk8s.png"],
  ["Micronaut", "micronaut.png"],
  ["Next.js", "nextjs.svg"],
  ["Node.js", "nodejs.svg"],
  ["Oracle Cloud", "oci.png"],
  ["Postman", "postman.svg"],
  ["Python", "python.svg"],
  ["React", "react.svg"],
  ["Rust", "rust.svg"],
  ["Terraform", "terraform.svg"],
  ["Typescript", "typescript.svg"],
  ["VirtualBox", "virtualbox.png"],
  ["Zig", "zig.svg"],
]);
